### PR TITLE
Editable Rich Text

### PR DESCRIPTION
**Pull request by rodydavis**

### CODE REVIEW

**Comment by rodydavis** [comment]
- Also Refactored Quite a bit to support the abstract classes and code duplication

**Comment by BaderEddineOuaich** [comment]
Great enhancements! 
Thanks @rodydavis

**Comment by BaderEddineOuaich** [comment]
Got pub.dev package errors:
<pre>
Fix lib/src/custom_text_field.dart. (-99.99 points)

Analysis of lib/src/custom_text_field.dart failed with 33 errors, 2 hints, including:

line 66 col 14: Case expressions must be constant.

line 66 col 29: The getter 'macOS' isn't defined for the class 'TargetPlatform'.

line 90 col 14: Case expressions must be constant.

line 90 col 29: The getter 'macOS' isn't defined for the class 'TargetPlatform'.

line 108 col 14: Case expressions must be constant.

Fix lib/src/flutter_syntax_edit.dart. (-1 points)

Analysis of lib/src/flutter_syntax_edit.dart reported 2 hints:

line 134 col 25: This function has a return type of 'bool', but doesn't end with a return statement.

line 165 col 27: This function has a return type of 'bool', but doesn't end with a return statement.

Format lib/src/syntaxes/javascript.dart.

Run flutter format to format lib/src/syntaxes/javascript.dart.
</pre>

looks like custom_text_field.dart has some conflicted code with the package

**Comment by rodydavis** [comment]
I’m doing this on master, what about you?

**Comment by BaderEddineOuaich** [comment]
There was a package in pub.dev and i got these erros after i updated it.
also the problem occurs in my machine when i try to test it fater the merge. 
have you faced any problem like that while you was testing ?

**Comment by rodydavis** [comment]
No I didn’t, but I can check today!

**Comment by BaderEddineOuaich** [comment]
Thanks! here's some info about the platform i work on:
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft
    Windows [Version 10.0.16299.1029], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at
      E:\Dev\SDKs\FlutterSDK\flutter
    • Framework revision 0b8abb4724 (12 days ago), 2020-02-11
      11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

**Pull request merged**
